mysql:
  Username: root
  Password: 10121125
  Host: 127.0.0.1
  Port: 3306
  DatabaseName: micro_shopping

UserService:
  Host: 127.0.0.1
  Port: 50001

CategoryService:
  Host: 127.0.0.1
  Port: 50002

ProductService:
  Host: 127.0.0.1
  Port: 50003

CartService:
  Host: 127.0.0.1
  Port: 50004

OrderService:
  Host: 127.0.0.1
  Port: 50005